name: jupyterlite-sphinx
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - scipy
  - seaborn
  - tabulate
  - xeus-python
  - pip:
    - ./jupyterlite/mock_libraries/numba
    - ./jupyterlite/mock_libraries/vtk
    - ..
